### ISSUE TITLE
Link to method directly with an anchor

### ISSUE THREAD

**Issue by SUPERCILEX** [droidchef/hops#2]
This is probably really hard, but it would be so awesome! Somehow, you would have to find the line # of the method and then link to it: `github.com/.../Foo.java#L10`.

**Comment by droidchef** [comment]
@SUPERCILEX Thanks for an awesome suggestion! 

I am actually converting this chrome extension into a stand alone Electron app because google has killed support for extensions.

Once I am done with that, I'll be happy to take this up! Or any help is welcome :D

**Comment by SUPERCILEX** [comment]
@droidchef Wait a sec, Google [isn't killing extensions](http://www.omgchrome.com/not-joke-google-killing-chrome-apps/)! Just Chrome Apps... I really like this app in extension form. 😄

![image](https://cloud.githubusercontent.com/assets/9490724/25315943/a565fa04-2812-11e7-887d-483b21db36c8.png)

**Comment by droidchef** [comment]
Holy Shit !!! I didn't know that. I probably misunderstood Apps as Extensions 🙈

Then I can come back to the feature requests, phew!! You made my day!! @SUPERCILEX

**Comment by SUPERCILEX** [comment]
@droidchef Glad to clear things up!!! 😄

**Comment by SUPERCILEX** [comment]
Closing old issues.
