### ISSUE TITLE
Link to standard Java and Android classes/documentation

### ISSUE THREAD

**Issue by ManojMadanmohan** [droidchef/hops#7]
Hi Ishan,

Firstly, loved the plugin. Thanks again!

One suggestion I had - while looking into someone else's source code on github, I sometimes come across android framework classes which I'm not particularly familiar with. It would be helpful if I could directly link to the either the source code or documentation of these classes. (Similar can be done for java classes as well) This could be maybe be enabled by default or via an option/setting.

Let me know what are your views on this.

If you think this makes sense, I could give it a shot (I haven't understood the source code completely, but I think it shouldn't be too difficult - Need to match for android.* packages and make changes around browseableClass I think - correct me if I am wrong)

**Comment by droidchef** [comment]
@ManojMadanmohan Sounds like a nice idea to me! Let the PRs rolle in ;)

**Comment by ManojMadanmohan** [comment]
Another thought - 

We could move this behind an interface actually, with the implementations returning the true/false if they can handle a package/class, and the url to link to if they can. Or instead, maybe move this information inside a configuration file. 

This way, people from the community can add in the required links for packages, and we could maybe have a settings/option on the UI to enable/disable each of these packages.

This is offcourse a bit complex; might take a lot of time.

For now, I've done the work for linking to android documentation; raising a PR shortly

**Comment by droidchef** [comment]
Fixed in #8
